name: Force publish to npm

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10.33.0
          run_install: false

      - run: pnpm install --frozen-lockfile
        env:
          HUSKY: 0

      - run: pnpm build

      - name: Set up .npmrc for publishing
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: pnpm exec nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
