name: Deploy Storybook to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6

      - run: pnpm install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build Storybook static site
        run: pnpm nx run @soundtouchjs/storybook:build-storybook

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./static-storybook

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
